---
title: "R Notebook"
output: html_notebook
---

## Procesos (Vectores Autorregresivos)VAR Estables

Sea el proceso VAR(p)
		$${Y}_t={\nu}+A_1 {Y}_{t-1} +\cdots+A_p {Y}_{t-p}+u_t, \  \  t=0,\pm1,\pm2,\cdots,$$
```{r simul VAR}
set.seed(123) 
# Generate sample
t <- 200 # Longitud de la serie
k <- 2 # dimensión del vector Y
p <- 2 # Número de retardos

# Matrices de coeficientes
A.1 <- matrix(c(-.3, .6, -.4, .5), k) # Matriz A1, retardo 1
A.2 <- matrix(c(-.1, -.2, .1, .05), k) # Matriz A2, retardo 2
A <- cbind(A.1, A.2) 

# Generación de la serie
series <- matrix(0, k, t + 2*p) # Condiciones iniciales
for (i in (p + 1):(t + 2*p)){ # Generar series con e ~ N(0,0.5)
  series[, i] <- A.1%*%series[, i-1] + A.2%*%series[, i-2] + rnorm(k, 0, .5)
}

series <- ts(t(series[, -(1:p)])) # Convertir a una serie con formato ts
names <- c("V1", "V2") # Renombrar las variables

plot.ts(series) # dibujarlas series
```

##Simulando usando tsDyn

```{r simul tsDyn}
library(tsDyn)
library(MTS)
set.seed(123) 
sig=.5
varcoverr=diag(sig,dim(A)[1])
var2=tsDyn::VAR.sim(A,n=200,lag=2,include="none",varcov=varcoverr) ###El vector de coeficientes debe ser parte de la matriz de coeficientes.
ts_var2=ts(var2)
plot(ts_var2)

```

```{r simul MTS}

intercept=c(rep(0,dim(A)[1]))
VAR2=MTS::VARMAsim(nobs = 200,arlags = c(2),cnst=intercept,phi = A,sigma=varcoverr)
ts_VAR2=ts(VAR2$series)
plot(ts_VAR2)

```
####Momentos
```{r momentos}
k=2
p=2
A.1 <- matrix(c(0.5, 0.4, 0.1, 0.5), k) # Matriz A1, retardo 1
A.2 <- matrix(c(0,0.25, 0, 0), k) # Matriz A2, retardo 2
A <- cbind(A.1, A.2) 
nu=matrix(c(1,2),nrow=k,ncol=1)
nu_big=rbind(nu,matrix(c(0,0),nrow=k,ncol=1))
I_big=diag(k*p)
A_big=rbind(A,cbind(diag(k),matrix(data = 0, nrow = k, ncol = k)))
mu_big=solve(I_big-A_big)%*%nu_big
eigen(A_big)
Mod(eigen(A_big)$values)
Sigma_big=rbind(cbind(varcoverr,matrix(data = 0, nrow = k, ncol = k)),cbind(matrix(data = 0, nrow = k, ncol = k),matrix(data = 0, nrow = k, ncol = k)))
J=cbind(diag(k),matrix(data = 0, nrow = k, ncol = k))
mu=J%*%mu_big
mu
```


### Procesos no estables


```{r no estables}
sig=.5

a11=1
a21=0.5
a12=0.6
a22=0.1
x11()
UnitCircle::uc.check(c(1,-(a11+a22),(a11*a22-a12*a21)))

A1_ne=matrix(c(a11,a21,a12,a22),2,2)
eigen(A1_ne)
intercept=c(rep(0,dim(A1_ne)[1]))
varcoverr=diag(sig,dim(A1_ne)[1])
VAR2_ne=MTS::VARMAsim(nobs = 200,arlags = c(1),cnst=intercept,phi = A1_ne,sigma=varcoverr)
ts_VAR2_ne=ts(VAR2_ne$series)
plot(ts_VAR2_ne)

```
### Autocovarianzas y Autocorrelaciones Teóricas

Note que la expresiones son 
$$vec(\Gamma_y(0))=(I_{K^2}-A_1\otimes A_1)^{-1}vec(\Sigma_u)$$

Así,

$$\Gamma_y(h)=A_1\Gamma_y(h-1)$$

```{r covarianzas y correlaciones teóricas}
a11=0.2
a21=-0.6
a12=0.3
a22=1.1

UnitCircle::uc.check(c(1,-(a11+a22),(a11*a22-a12*a21)))  ##Raíces por fuera del círculo Unitario
A=matrix(c(a11,a21,a12,a22),2,2)
Sigmau=matrix(c(1,0.8,0.8,2),2,2)
eigen(A)   ###Valores Propios por dentro del círculo unitario

###Conformación de los objetos
I4=diag(4) ## Create the 4-by-4 identity matrix
pp=kronecker(A,A) # Kronecker product
pp

c1=c(Sigmau)
c1

dd=I4-pp
ddinv=solve(dd)   ## Obtain inverse
gam0=ddinv%*%matrix(c1,4,1)  # Obtain Gamma_0
gam0

g0=matrix(gam0,2,2)
g1=A%*%g0     ## Obtain Gamma_1
g1


g2=A%*%g1
g2


###Correlaciones Cruzadas
D=diag(sqrt(diag(g0))) # To compute cross-correlation matrices
D

Di=solve(D)
Di%*%g0%*%Di

Di%*%g1%*%Di

Di%*%g1%*%Di

Di%*%g2%*%Di
```


## Pronósticos
$$
{Y}_t={\nu}+\begin{bmatrix}
		0.5&0&0\\
		0.1&0.1&0.3\\
		0&0.2&0.3
	\end{bmatrix}
	{Y}_{t-1}+{u}_t.
	$$
	
	con 
	
	$$\Sigma_{{u}}=\begin{bmatrix}
		2.25&0&0\\
		0.0&1.0&0.5\\
		0&0.5&0.74
	\end{bmatrix}$$
```{r pronósticos}
A1=matrix(c(0.5,0.1,0,0,0.1,0.2,0,0.3,0.3),3,3)
Sigma_u=matrix(c(2.25,0,0,0,1.0,0.5,0,0.5,0.74),3,3)
Sigma_y1=Sigma_u
Sigma_y2=Sigma_y1+A1%*%Sigma_u%*%t(A1)
Sigma_y3=Sigma_y2+(A1%*%A1)%*%Sigma_u%*%t(A1%*%A1)
```

Tarea: hacer lo mismo para el proceso VAR(2)
	\[
	{Y}_t={\nu}+\begin{bmatrix}
		0.5&0.1\\
		0.4&0.5
	\end{bmatrix}
	{Y}_{t-1}+\begin{bmatrix}
		0&0\\
		0.25&0
	\end{bmatrix}
	{Y}_{t-2}+{u}_t.
	\]
	
	con 
	
	$$\Sigma_{{u}}=\begin{bmatrix}
		0.09&0\\
		0.0&0.04\\
	\end{bmatrix}$$
	
	
###Intervalos de pronóstico



