---
title: "Importacion"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Creación de un objeto de Series de Tiempo y gráficas
## Serie de interés


```{r importacion}
tipos88 <- read.table("tipos88.dat", quote="\"", comment.char="")
Intanual=tipos88$V5  #Tipo de interés Anual
plot(as.ts(Intanual))
```
#Creando y graficando la serie de retornos para ver los cambios

```{r retornos interes}
camrelintanual=log(Intanual[2:length(Intanual)]/Intanual[1:(length(Intanual)-1)])
sercamrelint=ts(camrelintanual,start=c(1988,01),frequency=12)
sercamrelint
plot(sercamrelint)
acf(sercamrelint,ci.type='ma')
acf(sercamrelint,type='partial')
str(sercamrelint)
```

#Serie COLCAP


```{r Colcap}
library(xts)
library(readxl)
Colcap<- read_excel("Datos históricos COLCAP-3.xlsx")

TsColCap=xts(Colcap$Ultimo, order.by = as.Date(Colcap$Fecha, "%Y-%m-%d"))
plot(TsColCap)

acf(TsColCap)
str(TsColCap)
```

```{r TSstudio}
library(TSstudio)
data(EURO_Brent)
library(zoo)

ts_info(EURO_Brent)
class(EURO_Brent)####Es un objeto zoo y es una serie regularmente espaciada
head(index(EURO_Brent))
class(index(EURO_Brent))
attributes(index(EURO_Brent))
###Podemos cambiar la clase
index(EURO_Brent) <- as.Date(index(EURO_Brent))
head(EURO_Brent)
class(index(EURO_Brent))
```

